from django.contrib import admin, messages
from django.utils import timezone

from .models import (
    Domain,
    Feature,
    Plan,
    PlatformAdmin,
    Subscription,
    Tenant,
    TenantProvisioning,
)


class DomainInline(admin.TabularInline):
    model = Domain
    extra = 0
    fields = ("domain", "is_primary", "verified", "verified_at")
    readonly_fields = ("verified_at",)


class SubscriptionInline(admin.TabularInline):
    model = Subscription
    extra = 0
    fields = ("plan", "status", "starts_at", "ends_at", "trial_ends_at")
    show_change_link = True


@admin.register(Feature)
class FeatureAdmin(admin.ModelAdmin):
    list_display = ("code", "name", "is_active")
    list_filter = ("is_active",)
    search_fields = ("code", "name")
    prepopulated_fields = {"code": ("name",)}


@admin.register(Plan)
class PlanAdmin(admin.ModelAdmin):
    list_display = ("name", "code", "max_employees", "max_branches", "is_active")
    list_filter = ("is_active",)
    search_fields = ("code", "name")
    filter_horizontal = ("features",)
    prepopulated_fields = {"code": ("name",)}


@admin.register(Tenant)
class TenantAdmin(admin.ModelAdmin):
    list_display = ("name", "schema_name", "status", "contact_email", "created_at")
    list_filter = ("status",)
    search_fields = ("name", "schema_name", "contact_email", "domains__domain")
    readonly_fields = ("schema_name", "created_at")
    raw_id_fields = ("owner",)
    inlines = [DomainInline, SubscriptionInline]

    def get_readonly_fields(self, request, obj=None):
        # schema_name is generated by the provisioning service; never edit it
        # on an existing tenant. Creating tenants should go through onboarding.
        if obj is None:
            return ("created_at",)
        return self.readonly_fields

    def has_delete_permission(self, request, obj=None):
        # Deleting a tenant row must be a deliberate, scripted operation.
        return False


@admin.register(Domain)
class DomainAdmin(admin.ModelAdmin):
    list_display = ("domain", "tenant", "is_primary", "verified", "verified_at")
    list_filter = ("verified", "is_primary")
    search_fields = ("domain", "tenant__name", "tenant__schema_name")
    readonly_fields = ("verification_token", "verified_at", "created_at")
    actions = ["mark_verified"]

    @admin.action(description="Mark selected domains as verified")
    def mark_verified(self, request, queryset):
        updated = queryset.filter(verified=False).update(verified=True, verified_at=timezone.now())
        self.message_user(request, f"{updated} domain(s) marked as verified.", messages.SUCCESS)


@admin.register(Subscription)
class SubscriptionAdmin(admin.ModelAdmin):
    list_display = ("tenant", "plan", "status", "starts_at", "ends_at", "trial_ends_at")
    list_filter = ("status", "plan")
    search_fields = ("tenant__name", "tenant__schema_name", "billing_email")
    autocomplete_fields = ("tenant",)
    filter_horizontal = ("features",)
    date_hierarchy = "starts_at"


@admin.register(TenantProvisioning)
class TenantProvisioningAdmin(admin.ModelAdmin):
    list_display = (
        "organization_name", "slug", "custom_domain", "status",
        "applicant", "requested_plan", "created_at",
    )
    list_filter = ("status", "wants_custom_website", "requested_plan")
    search_fields = ("organization_name", "slug", "custom_domain", "email", "applicant__email")
    date_hierarchy = "created_at"
    raw_id_fields = ("applicant", "reviewed_by", "tenant")
    readonly_fields = (
        "id", "applicant", "status", "reviewed_by", "reviewed_at", "tenant",
        "provision_error", "created_at", "updated_at",
    )
    fieldsets = (
        ("Organization", {"fields": ("organization_name", "logo", "email", "contact_phone", "address", "branches")}),
        ("Hosting", {"fields": ("slug", "custom_domain", "wants_custom_website", "ops_admin_email", "requested_plan")}),
        ("Review", {"fields": ("id", "applicant", "status", "review_notes", "reviewed_by", "reviewed_at")}),
        ("Provisioning", {"fields": ("tenant", "provision_error", "created_at", "updated_at")}),
    )
    actions = ["reject_requests"]

    @admin.action(description="Reject selected requests (submitted only)")
    def reject_requests(self, request, queryset):
        updated = queryset.filter(status=TenantProvisioning.Status.SUBMITTED).update(
            status=TenantProvisioning.Status.REJECTED,
            reviewed_by=request.user,
            reviewed_at=timezone.now(),
        )
        self.message_user(request, f"{updated} request(s) rejected.", messages.SUCCESS)

    def has_add_permission(self, request):
        # Requests come from the public onboarding API, not the admin.
        return False


@admin.register(PlatformAdmin)
class PlatformAdminAdmin(admin.ModelAdmin):
    list_display = ("user", "title", "created_at")
    search_fields = ("user__email", "title")
    raw_id_fields = ("user",)